development:
  adapter: postgresql
  database: hotdealio_dev
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: hotdealio
  host: localhost
  pool: 5
  timeout: 5000